// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPISuperheroUniverse.DBContext.EntityFramework;

#nullable disable

namespace WebAPISuperheroUniverse.DBContext.EntityFramework.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelBattle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BattleDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("Hero1Id")
                        .HasColumnType("int");

                    b.Property<int>("Hero1Score")
                        .HasColumnType("int");

                    b.Property<int>("Hero2Id")
                        .HasColumnType("int");

                    b.Property<int>("Hero2Score")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_xtBattles");

                    b.HasIndex("BattleDate")
                        .IsDescending()
                        .HasDatabaseName("IX_xtBattles_BattleDate");

                    b.HasIndex("Hero1Id")
                        .HasDatabaseName("IX_xtBattles_Hero1Id");

                    b.HasIndex("Hero2Id")
                        .HasDatabaseName("IX_xtBattles_Hero2Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("xtBattles", null, t =>
                        {
                            t.HasCheckConstraint("CK_xtBattles_DistinctHeroes", "[Hero1Id] <> [Hero2Id]");
                        });
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelMission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("RequiredHeroCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK_xtMissions");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_xtMissions_Status");

                    b.ToTable("xtMissions", null, t =>
                        {
                            t.HasCheckConstraint("CK_xtMissions_Difficulty", "[Difficulty] IN (N'Easy', N'Medium', N'Hard')");

                            t.HasCheckConstraint("CK_xtMissions_RequiredHeroCount", "[RequiredHeroCount] > 0");

                            t.HasCheckConstraint("CK_xtMissions_Status", "[Status] IN (N'Pending', N'InProgress', N'Success', N'Failed')");
                        });
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelMissionHero", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("SuperheroId")
                        .HasColumnType("int");

                    b.HasKey("MissionId", "SuperheroId")
                        .HasName("PK_xtMissionHeroes");

                    b.HasIndex("SuperheroId")
                        .HasDatabaseName("IX_xtMissionHeroes_SuperheroId");

                    b.ToTable("xtMissionHeroes", (string)null);
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelPower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_xtPowers");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_xtPowers_Name");

                    b.ToTable("xtPowers", (string)null);
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_xtRoles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_xtRoles_Name");

                    b.ToTable("xtRoles", (string)null);
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelSuperhero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Combat")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durability")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PowerLevel")
                        .HasColumnType("int");

                    b.Property<string>("RealName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<string>("Universe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id")
                        .HasName("PK_xtSuperheroes");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_xtSuperheroes_Name");

                    b.HasIndex("PowerLevel")
                        .IsDescending()
                        .HasDatabaseName("IX_xtSuperheroes_PowerLevel");

                    b.HasIndex("Universe", "Alignment")
                        .HasDatabaseName("IX_xtSuperheroes_Universe_Alignment");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Universe", "Alignment"), new[] { "PowerLevel" });

                    b.ToTable("xtSuperheroes", null, t =>
                        {
                            t.HasCheckConstraint("CK_xtSuperheroes_Alignment", "[Alignment] IN (N'Hero', N'Villain', N'Anti-Hero')");

                            t.HasCheckConstraint("CK_xtSuperheroes_Combat", "[Combat] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_xtSuperheroes_Durability", "[Durability] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_xtSuperheroes_Intelligence", "[Intelligence] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_xtSuperheroes_PowerLevel", "[PowerLevel] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_xtSuperheroes_Speed", "[Speed] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_xtSuperheroes_Strength", "[Strength] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelSuperheroPower", b =>
                {
                    b.Property<int>("SuperheroId")
                        .HasColumnType("int");

                    b.Property<int>("PowerId")
                        .HasColumnType("int");

                    b.HasKey("SuperheroId", "PowerId")
                        .HasName("PK_xtSuperheroPowers");

                    b.HasIndex("PowerId")
                        .HasDatabaseName("IX_xtSuperheroPowers_PowerId");

                    b.ToTable("xtSuperheroPowers", (string)null);
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelSuperheroTeam", b =>
                {
                    b.Property<int>("SuperheroId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("JoinedDate")
                        .HasColumnType("date");

                    b.HasKey("SuperheroId", "TeamId")
                        .HasName("PK_xtSuperheroTeams");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX_xtSuperheroTeams_TeamId");

                    b.ToTable("xtSuperheroTeams", (string)null);
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("FoundedDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Universe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_xtTeams");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_xtTeams_Name");

                    b.HasIndex("Universe")
                        .HasDatabaseName("IX_xtTeams_Universe");

                    b.ToTable("xtTeams", (string)null);
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_xtUsers");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_xtUsers_Email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UQ_xtUsers_Username");

                    b.ToTable("xtUsers", (string)null);
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK_xtUserRoles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_xtUserRoles_RoleId");

                    b.ToTable("xtUserRoles", (string)null);
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelBattle", b =>
                {
                    b.HasOne("WebAPISuperheroUniverse.Entities.Tables.ModelSuperhero", "Hero1")
                        .WithMany()
                        .HasForeignKey("Hero1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_xtBattles_Hero1");

                    b.HasOne("WebAPISuperheroUniverse.Entities.Tables.ModelSuperhero", "Hero2")
                        .WithMany()
                        .HasForeignKey("Hero2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_xtBattles_Hero2");

                    b.HasOne("WebAPISuperheroUniverse.Entities.Tables.ModelSuperhero", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_xtBattles_Winner");

                    b.Navigation("Hero1");

                    b.Navigation("Hero2");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelMissionHero", b =>
                {
                    b.HasOne("WebAPISuperheroUniverse.Entities.Tables.ModelMission", "Mission")
                        .WithMany("MissionHeroes")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_xtMissionHeroes_xtMissions");

                    b.HasOne("WebAPISuperheroUniverse.Entities.Tables.ModelSuperhero", "Superhero")
                        .WithMany("MissionHeroes")
                        .HasForeignKey("SuperheroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_xtMissionHeroes_xtSuperheroes");

                    b.Navigation("Mission");

                    b.Navigation("Superhero");
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelSuperheroPower", b =>
                {
                    b.HasOne("WebAPISuperheroUniverse.Entities.Tables.ModelPower", "Power")
                        .WithMany("SuperheroPowers")
                        .HasForeignKey("PowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_xtSuperheroPowers_xtPowers");

                    b.HasOne("WebAPISuperheroUniverse.Entities.Tables.ModelSuperhero", "Superhero")
                        .WithMany("SuperheroPowers")
                        .HasForeignKey("SuperheroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_xtSuperheroPowers_xtSuperheroes");

                    b.Navigation("Power");

                    b.Navigation("Superhero");
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelSuperheroTeam", b =>
                {
                    b.HasOne("WebAPISuperheroUniverse.Entities.Tables.ModelSuperhero", "Superhero")
                        .WithMany("SuperheroTeams")
                        .HasForeignKey("SuperheroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_xtSuperheroTeams_xtSuperheroes");

                    b.HasOne("WebAPISuperheroUniverse.Entities.Tables.ModelTeam", "Team")
                        .WithMany("SuperheroTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_xtSuperheroTeams_xtTeams");

                    b.Navigation("Superhero");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelUserRole", b =>
                {
                    b.HasOne("WebAPISuperheroUniverse.Entities.Tables.ModelRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_xtUserRoles_xtRoles");

                    b.HasOne("WebAPISuperheroUniverse.Entities.Tables.ModelUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_xtUserRoles_xtUsers");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelMission", b =>
                {
                    b.Navigation("MissionHeroes");
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelPower", b =>
                {
                    b.Navigation("SuperheroPowers");
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelSuperhero", b =>
                {
                    b.Navigation("MissionHeroes");

                    b.Navigation("SuperheroPowers");

                    b.Navigation("SuperheroTeams");
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelTeam", b =>
                {
                    b.Navigation("SuperheroTeams");
                });

            modelBuilder.Entity("WebAPISuperheroUniverse.Entities.Tables.ModelUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
